apiVersion: v2
name: notizblock-app-chart
description: A Helm chart for the React Docker Notizblock Full-Stack application
type: application 
version: 0.1.0 
appVersion: "1.0.0" 

dependencies:
  - name: postgresql
    version: "16.7.8" 
    repository: "https://charts.bitnami.com/bitnami"
    alias: database 