apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-notizblock
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend-notizblock
  template:
    metadata:
      labels:
        app: backend-notizblock
    spec:
      containers:
        - name: backend
          image: sebriede66/mein-notizblock-backend:latest 
          ports:
            - containerPort: 3000 
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "postgres-db-service" 
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret 
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: LOG_LEVEL
              value: "info"
          readinessProbe: 
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20 
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe: 
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service 
spec:
  type: ClusterIP 
  ports:
    - port: 3000 
      targetPort: 3000 
  selector:
    app: backend-notizblock