apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notizblock-app-chart.fullname" . }}-backend-db-creds
  labels:
    {{- include "notizblock-app-chart.labels" . | nindent 4 }}
type: Opaque
stringData: 
  DB_USER: {{ .Values.database.auth.username | quote }}
  DB_PASSWORD: {{ .Values.database.auth.password | quote }}
  DB_NAME: {{ .Values.database.auth.database | quote }}