{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notizblock-app-chart.fullname" . }}-backend
  labels:
    {{- include "notizblock-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "notizblock-app-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "notizblock-app-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.env.PORT | int }} 
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.backend.env.PORT | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.backend.env.LOG_LEVEL | quote }}
            - name: DB_HOST
              
              value: {{ .Values.backend.env.DB_HOST_OVERRIDE | default (printf "%s-%s" .Release.Name ( .Values.database.overrideName | default .Values.database.alias | default "database")) | quote }}
            - name: DB_PORT
              value: {{ .Values.backend.env.DB_PORT | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "notizblock-app-chart.fullname" . }}-backend-db-creds
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "notizblock-app-chart.fullname" . }}-backend-db-creds
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "notizblock-app-chart.fullname" . }}-backend-db-creds
                  key: DB_NAME
          {{- if .Values.backend.probes.liveness.path }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.backend.probes.readiness.path }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}
          {{- end }}
          resources: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notizblock-app-chart.fullname" . }}-backend
  labels:
    {{- include "notizblock-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http 
      protocol: TCP
      name: http
  selector:
    {{- include "notizblock-app-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}