{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notizblock-app-chart.fullname" . }}-frontend
  labels:
    {{- include "notizblock-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "notizblock-app-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "notizblock-app-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80 
              protocol: TCP
          
          resources: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notizblock-app-chart.fullname" . }}-frontend
  labels:
    {{- include "notizblock-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http 
      protocol: TCP
      name: http
  selector:
    {{- include "notizblock-app-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}